package de.bitapp.paper.page;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-12T15:11:02.929+09:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "pageService", 
                  wsdlLocation = "file:/C:/Users/bond/git/PaperTest3/paper3.wsdl",
                  targetNamespace = "http://paper.bitapp.de/page") 
public class PageService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://paper.bitapp.de/page", "pageService");
    public final static QName PageServicePort = new QName("http://paper.bitapp.de/page", "pageServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/bond/git/PaperTest3/paper3.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PageService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/bond/git/PaperTest3/paper3.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PageService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PageService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PageService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PageService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PageService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PageServicePortType
     */
    @WebEndpoint(name = "pageServicePort")
    public PageServicePortType getPageServicePort() {
        return super.getPort(PageServicePort, PageServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PageServicePortType
     */
    @WebEndpoint(name = "pageServicePort")
    public PageServicePortType getPageServicePort(WebServiceFeature... features) {
        return super.getPort(PageServicePort, PageServicePortType.class, features);
    }

}
