package de.bitapp.paper.page;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-12T15:11:02.919+09:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://paper.bitapp.de/page", name = "pageServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PageServicePortType {

    @WebResult(name = "Status", targetNamespace = "http://paper.bitapp.de/page", partName = "Status")
    @WebMethod(operationName = "Ping", action = "Ping")
    public CodeType ping(
        @WebParam(partName = "Status", name = "Status")
        FileType status
    );
}
